### ISSUE TITLE
Unable to restore a deleted file - Can't find the right timestamp ?

### ISSUE THREAD

**Issue by meepmeep** [bulletmark/b2restore#1]
Hi @bulletmark  ! 

I recently migrated to rclone + b2, and it looks very great, however, before lauching it into production, I'm running some dummy case of "Oops I deleted everything / Oops My hard drive failed / etc." and try to restore my data.

With the hidden's files from b2, your tool looks like the perfect solution to re-create a perfect directory tree with all the correct filename.

Example : 

I sync my b2 bucket with deleted file (TEST.TXT) locally
```
root@Daenerys:~/rclone/TMP# rclone sync --b2-versions b2:dxxxxxxxx/University/exam b2files
root@Daenerys:~/rclone/TMP# cd b2files/
root@Daenerys:~/rclone/TMP/b2files# ls
q2.txt  q3.txt  q4.txt  q5.txt  q6.txt  réponses.txt  TEST-v2021-10-20-132346-000.TXT
```
TEST.TXT has correctly been hidden by b2, great, my data are safe :)
Let's try to recreate a perfect directory
```
root@Daenerys:~/rclone/TMP/b2files# cd ..
root@Daenerys:~/rclone/TMP# b2restore b2files outdir
creating 2011-08-31T22:58.24: q6.txt
creating 2011-08-31T22:58.24: q5.txt
creating 2011-08-31T22:58.24: q3.txt
creating 2011-08-31T22:58.24: q4.txt
creating 2011-08-31T22:58.24: q2.txt
creating 2011-08-31T22:58.24: réponses.txt
```
ok, "last" version means b2restore don't try to restore deleted file. 
```
root@Daenerys:~/rclone/TMP# rm -rf outdir/
root@Daenerys:~/rclone/TMP# b2restore -s  b2files outdir
TEST.TXT:
  2021-10-20T15:23.42      208 B
q2.txt:
  2011-08-31T22:58.24     1278 B
q3.txt:
  2011-08-31T22:58.24     1433 B
q4.txt:
  2011-08-31T22:58.24     1196 B
q5.txt:
  2011-08-31T22:58.24     1558 B
q6.txt:
  2011-08-31T22:58.24     1305 B
réponses.txt:
  2011-08-31T22:58.24      208 B
```
I tried with different timestamp (before / after the file was modified). But in each case, I still can't get b2restore to create a TEST.TXT file.
Exact time of the timestamp :
```
root@Daenerys:~/rclone/TMP# b2restore -t 2021-10-20T15:23.42  b2files outdir
creating 2011-08-31T22:58.24: q6.txt
creating 2011-08-31T22:58.24: q5.txt
creating 2011-08-31T22:58.24: q3.txt
creating 2011-08-31T22:58.24: q4.txt
creating 2011-08-31T22:58.24: q2.txt
creating 2011-08-31T22:58.24: réponses.txt
```
1 min before
```
root@Daenerys:~/rclone/TMP# b2restore -t 2021-10-20T15:22.42  b2files outdir
```
1 min after 
```
root@Daenerys:~/rclone/TMP# b2restore -t 2021-10-20T15:24.42  b2files outdir
root@Daenerys:~/rclone/TMP# ls -lh outdir/
total 24K
-rw-r--r-- 2 root root 1.3K Aug 31  2011 q2.txt
-rw-r--r-- 2 root root 1.4K Aug 31  2011 q3.txt
-rw-r--r-- 2 root root 1.2K Aug 31  2011 q4.txt
-rw-r--r-- 2 root root 1.6K Aug 31  2011 q5.txt
-rw-r--r-- 2 root root 1.3K Aug 31  2011 q6.txt
-rw-r--r-- 2 root root  208 Aug 31  2011 réponses.txt
```

How could I restore my TEST.TXT and all other existing file ? I'm missing something obvious I think ..

**Comment by bulletmark** [comment]
It appears this was never working properly but I believe I have fixed it now. However, there is a small limitation which I added a [new section](https://github.com/bulletmark/b2restore#limitations) about in the README and you should read. Please try this new version and let me know how you go.
