### ISSUE TITLE
Why are deleted files not kept deleted for restores?

### ISSUE THREAD

**Issue by Awbmilne** [bulletmark/b2restore#3]
Hey, this seems like an awesome tool and adds to my confidence in using B2 versioning to keep old versions.

This primary advantage for me to using BackBlaze's Lifecycle instead of rclone's `--backup-dir` is that I can create a BackBlaze access key that cannot permanently delete files. This is a great setup to avoid propogation of ransomware on my device to the BackBlaze data.

My question is, Why are deleted (hidden) files not left out of restores?
In your example in the readme, you say that a restore for Jan 02 would remake `a.txt`.
I dont understand what causes this limitation. The BackBlaze API provides an `action` value for each version in the `b2_list_file_versions` operation. A `hidden` value is provided for any version where the file is hidden (soft-deleted). So it should be possible to detect deletions. Is this limitation an outcome of Rclone's reporting of the files states?

Thanks! Would love to eradicate that limitation.

**Comment by bulletmark** [comment]
This utility is only ever intended to be based on `rclone`. Have no intention to use the BackBlaze API so closing.
